version: 2
jobs:
  build:
    working_directory: ~/repo/impl-2021
    docker:
      - image: circleci/node:14.17.5
      - image: trufflesuite/ganache-cli
        command: ganache-cli -i 5777 -p 7545
    steps:
      - checkout:
          path: "~/repo"
      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Migrate Contracts
          command: yarn truffle migrate --network=development --contracts_build_directory="$PWD/build/dev/contracts"
      - run:
          name: Tests Contracts
          command: yarn truffle test

